name: cs175project
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.3=pyhe01879c_0
  - cyrus-sasl=2.1.28=h83b0a09_4
  - debugpy=1.8.20=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=h7354ed3_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.14.1=hf5b9546_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=12.3.0=h79d275a_1
  - icu=73.1=h6a678d5_0
  - ipykernel=7.2.0=pyha191276_0
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcups=2.4.15=hbe4054b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.22.1=h6d2bf13_0
  - libllvm15=15.0.7=he89c38a_4
  - libnsl=2.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=17.6=h5ca1609_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mesalib=25.1.5=h31e3550_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py311h06a4308_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311haee01d2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyqt=6.9.1=py311hc79087c_0
  - pyqt6-sip=13.10.2=py311hee96239_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - qtbase=6.9.2=h1fa0d2d_6
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - sip=6.12.0=py311h7934f7d_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py311h41d9c34_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.46.3=py311h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - coloredlogs==15.0.1
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - daemoniker==0.2.3
      - dill==0.4.1
      - farama-notifications==0.0.4
      - filelock==3.20.3
      - flaky==3.8.1
      - fsspec==2026.2.0
      - getch==1.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - humanfriendly==10.0
      - idna==3.11
      - imagehash==4.3.2
      - inflection==0.5.1
      - jinja2==3.1.6
      - lxml==6.0.2
      - markupsafe==3.0.3
      - minerl==1.0.2
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - pillow==12.1.0
      - pip==26.0.1
      - pyglet==2.1.13
      - pyro4==4.82
      - pywavelets==1.8.0
      - requests==2.32.5
      - scipy==1.15.3
      - serpent==1.42
      - setuptools==81.0.0
      - sympy==1.14.0
      - torch==2.10.0
      - tqdm==4.67.3
      - triton==3.6.0
      - typing==3.7.4.3
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - xmltodict==0.12.0
prefix: /home/john/miniconda3/envs/cs175project
