###########
# site.title

title:    'MCSRAI: A Minecraft Speedrunning AI'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
